/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
"clear-day", "clear-night", "partly-cloudy-day",
            "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
            "fog"
var date,highTemp,lowTemp,weather;

  // you can add a canvas by it's ID...

  // start animation!*/
  skycons.play();
  
/*
Get value from Bootstrap dropdown menublr
*/
$('button').click(function(){
  $('a').each(function(index, element){    
      $.getJSON(getCityJSON($(element).attr('data')),function(data){
        var cityTemp = data.query.results.channel.item.condition.temp;
        $(element).children('span').text(changeCelsius(cityTemp)+ "˚C"); 
      });
  });
});

$('#dropdown li a').on('click', function(){
    // alert($(this).attr("data"));
    getJSONInform(getCityJSON($(this).attr("data")));
    $('button').text($(this).text().slice(0,3));
});

var getCityJSON = function(city){
  var cityName = city.split(' ');
  return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + cityName[0] + "%20" + cityName[1] + "%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys"
};

var getJSONInform = function(url){
  $.getJSON(url ,function(data){
    console.log (data) ; // 可以比較方便你找到你要的資料在這個物件的哪個位置

    //-------------------把參數跟text.skycons set group起來,寫成一個function-----------------------//
    var curTemp = data.query.results.channel.item.condition.temp  ;
    var curDate = data.query.results.channel.item.forecast[0].date;
    var curWeather = data.query.results.channel.item.condition.text;
    
    function todaySet(){  
      $('.date').text(curDate);
      $('.weather').text(curWeather);
      $('.temperature').text(changeCelsius(curTemp));    
      skyconSet("today",curWeather);
      console.log("todayset done");
    };

    function skyconSet(orderOfDay,condition){  
      if(condition == "Cloudy" || condition == "Mostly Cloudy" || condition == "Partly Cloudy") {
        skycons.set(orderOfDay, Skycons.CLOUDY);
      }else if(condition == "Sunny" || condition == "Fair") {
          skycons.set(orderOfDay,Skycons.CLEAR_DAY);
      }else if(condition == "Rain" || condition =="Thunderstorms" || condition == "Showers" || condition == "Scattered Thunderstorms"){
          skycons.set(orderOfDay, Skycons.RAIN);
      }else if(condition == "Fog"){
          skycons.set(orderOfDay, Skycons.FOG);
      }else if(condition == "Windy"|| condition == "Breezy"){
          skycons.set(orderOfDay, Skycons.WIND);
      }; 
    };

    function forecastSet(i , orderOfDay){
      date = data.query.results.channel.item.forecast[i].date;
      highTemp = data.query.results.channel.item.forecast[i].high;
      lowTemp = data.query.results.channel.item.forecast[i].low;
      weather = data.query.results.channel.item.forecast[i].text;

      $('.forecast-date > th:nth-child('+i+')').text(date);
      $('.forecast-temperature > td:nth-child('+i+')').text(changeCelsius(lowTemp) + "-" + changeCelsius(highTemp) + "˚C" +" "+weather);
      $("#"+orderOfDay).text(weather);
      skyconSet(orderOfDay,weather);
      console.log("forecastset"+i+" done");
    };

    todaySet();
    forecastSet(1,"day1");
    forecastSet(2,"day2");
    forecastSet(3,"day3");
  });
};


getJSONInform(getCityJSON("taipei city"));

var changeCelsius = function(temp){
  return Math.round(((temp - 32) * 5) / 9);
};