/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();
"clear-day", "clear-night", "partly-cloudy-day",
            "partly-cloudy-night", "cloudy", "rain", "sleet", "snow", "wind",
            "fog"

  // you can add a canvas by it's ID...
  
  //------------------讓這段code變得有意義-------------------------//

  skycons.add("today", Skycons.PARTLY_CLOUDY_DAY);
  skycons.add("day1", Skycons.CLEAR_DAY);
  skycons.add("day2", Skycons.CLOUDY);
  skycons.add("day3", Skycons.RAIN);

  // start animation!
  skycons.play();  
  // want to change the icon? no problem:
  skycons.set("today", Skycons.PARTLY_CLOUDY_NIGHT);
  
/*
Get value from Bootstrap dropdown menublr
*/
$('button').click(function(){
  $('a').each(function(index, element){    
      $.getJSON(getCityJSON($(element).attr('data')),function(data){
        var cityTemp = data.query.results.channel.item.condition.temp;
        $(element).children('span').text(changeCelsius(cityTemp)+ "˚C"); 
      });
  });
});

$('#dropdown li a').on('click', function(){
    // alert($(this).attr("data"));
    getJSONInform(getCityJSON($(this).attr("data")));
    $('button').text($(this).text().slice(0,3));
});

var getCityJSON = function(city){
  var cityName = city.split(' ');
  return "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22" + cityName[0] + "%20" + cityName[1] + "%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys"
};

var getJSONInform = function(url){
  $.getJSON(url ,function(data){
    console.log (data) ; // 可以比較方便你找到你要的資料在這個物件的哪個位置

    //-------------------把參數跟text.skycons set group起來,寫成一個function-----------------------//

    var curTemp = data.query.results.channel.item.condition.temp  ;
    var curDate = data.query.results.channel.item.forecast[0].date;
    var curWeather = data.query.results.channel.item.condition.text;

    var secDate = data.query.results.channel.item.forecast[1].date;
    var secHighTemp = data.query.results.channel.item.forecast[1].high;
    var secLowTemp = data.query.results.channel.item.forecast[1].low;
    var secWeather = data.query.results.channel.item.forecast[1].text;

    var thirdDate = data.query.results.channel.item.forecast[2].date;
    var thirdHighTemp = data.query.results.channel.item.forecast[2].high;
    var thirdLowTemp = data.query.results.channel.item.forecast[2].low;
    var thirdWeather = data.query.results.channel.item.forecast[2].text;

    var fourthDate = data.query.results.channel.item.forecast[3].date;
    var fourthHighTemp = data.query.results.channel.item.forecast[3].high;
    var fourthLowTemp = data.query.results.channel.item.forecast[3].low;
    var fourthWeather = data.query.results.channel.item.forecast[3].text;


    $('.date').text(curDate);
    $('.weather').text(curWeather);
    $('.temperature').text(changeCelsius(curTemp));    
    skyconSet("today",curWeather);

    $('.forecast-date > th:first-child').text(secDate);
    $('.forecast-temperature > td:first-child').text(changeCelsius(secLowTemp) + "-" + changeCelsius(secHighTemp) + "˚C" +" "+secWeather);
    $('.forecast-weather > td > #day1').text(secWeather);    
    skyconSet("day1",secWeather);

    $('.forecast-date > th:nth-child(2)').text(thirdDate);
    $('.forecast-temperature > td:nth-child(2)').text(changeCelsius(thirdLowTemp) + "-" + changeCelsius(thirdHighTemp) + "˚C"+ " " + thirdWeather);
    $('.forecast-weather > td > #day2').text(thirdWeather);
    skyconSet("day2",thirdWeather);

    $('.forecast-date > th:last-child').text(fourthDate);
    $('.forecast-temperature > td:last-child').text(changeCelsius(fourthLowTemp) + "-" + changeCelsius(fourthHighTemp) + "˚C" + " " + fourthWeather);
    $('.forecast-weather > td > #day3').text(fourthWeather);
    skyconSet("day3",fourthWeather);
  });


  //------------------------判斷式再完整---------------------------//

  var skyconSet = function(orderOfDay,condition){  
    if(condition == "Cloudy") {
        skycons.set(orderOfDay, Skycons.CLOUDY);
    }else if(condition == "Sunny") {
      skycons.set(orderOfDay,Skycons.CLEAR_day);
    }else if(condition == "Rain" || condition == "Thunderstorms" || condition == "Showers" || condition == "Scattered Thunderstorms"){
      skycons.set(orderOfDay, Skycons.RAIN);
    }else if(condition == "Fog"){
      skycons.set(orderOfDay, Skycons.FOG);
    }else if(condition == "Wind"){
      skycons.set(orderOfDay, Skycons.WIND);
    };
  };
};


getJSONInform(getCityJSON("taipei city"));

var changeCelsius = function(temp){
  return Math.round(((temp - 32) * 5) / 9);
};


